server:
  port: 5000

spring:
  application:
    name: spring-server

  datasource:
    url: jdbc:mysql://remotemysql.com:3306/equ9yO6p8J?useSSL=false&useUnicode=yes&characterEncoding=UTF-8&allowPublicKeyRetrieval=true&serverTimezone=UTC&createDatabaseIfNotExist=true
    username: equ9yO6p8J
    password: c3Qx3hl6sU

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

    hibernate:
      ddl-auto: update

